### ISSUE TITLE
Can't understand what function "get_inverse_hvp_lissa" do 

### ISSUE THREAD

**Issue by jiqiujia** [kohpangwei/influence-release#4]
It seems a little different with the illustration in paper.
I don't understand why do we need parameter `damping` and `scale.`
Escecially, how to understand this line of code
`cur_estimate = [a + (1-damping) * b - c/scale for (a,b,c) in zip(v, cur_estimate, hessian_vector_val)]`

**Comment by kohpangwei** [comment]
The `scale` parameter scales the maximum eigenvalue to < 1 so that our Taylor approximation converges (see footnote 2, page 4 of [our paper](https://arxiv.org/pdf/1703.04730.pdf); it's also mentioned in the [original LiSSA paper](https://arxiv.org/abs/1602.03943)). The `damping` parameter is discussed in section 4.2 of our paper.

**Comment by Shehz** [comment]
`cur_estimate = [a + (1-damping) * b - c/scale for (a,b,c) in zip(v, cur_estimate, hessian_vector_val)]`
According to paper, is it the above equation to be 
`cur_estimate = [a + (1-damping) * b*a - (c*a)/scale for (a,b,c) in zip(v, cur_estimate, hessian_vector_val)]`
